include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    file_names: error
    prefer_relative_imports: error
    non_constant_identifier_names: error
    camel_case_types: error
    unnecessary_null_checks: error
